export const Assets = {
    happy: "./images/happy.png",
    happy1: "./images/happy1.png",
    workmom: "./images/workmom.png",
    family: "./images/family.png",
    feature1: "./images/feature1.jpeg",
    feature2: "./images/feature2.jpeg",
    feature3: "./images/feature3.png",
    staff: "./images/staff.png",
    path1: "./images/path1.jpeg",
    path2: "./images/path2.jpeg",
    path3: "./images/path3.jpeg",
    path4: "./images/path4.jpeg",
    pathology: "./images/pathology.png",
    foreground: "./images/foreground.png",
    background: "./images/background.png",
    support1: "./images/support.png",
    social: "./images/social.png",
    operate: "./images/operate.jpeg",
    support: "./images/support.jpeg",
    temperature: "./images/temperature.jpeg",
    comfort: "./images/comfort.jpeg",
    contactUs: "./images/contact-us.jpeg",
    examine: "./images/examine.png",
    newLife: "./images/new-life.jpeg",
    bgImage: "./images/bgImage.jpeg",
}