export const Assets = {
    happy: "/images/happy.png",
    workmom: "/images/workmom.png",
    family: "/images/family.png",
    feature1: "/images/feature1.jpeg",
    feature2: "/images/feature2.jpeg",
    feature3: "/images/feature3.png",
    staff: "/images/staff.png",
    path1: "/images/path1.jpeg",
    path2: "/images/path2.jpeg",
    path3: "/images/path3.jpeg",
    path4: "/images/path4.jpeg",
    pathology: "/images/pathology.png",
    foreground: "/images/foreground.png",
    background: "/images/background.png",
}